---
- hosts: all
  gather_facts: false
  vars_files:
    - vars.yml

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
  - include_tasks: 'tasks/base.yml'
  - include_tasks: 'tasks/floppy.yml'
  
  - name: "Set VCenter Addr"
    set_fact:
      vcenter_address: '{{ hostvars[inventory_hostname]["inventory_hostname"] }}'
    when: vcenter_address is undefined

  - name: Add vSphere
    add_host:
      name: '{{ vcenter_address }}'
      group: "vSphere"

- hosts: 'vSphere'
  gather_facts: false
  vars_files:
    - vars.yml

  vars:
    
    ansible_python_interpreter: "/usr/bin/python3"
    vcenter_address: '{{ hostvars[inventory_hostname]["inventory_hostname"] }}'

  tasks:
  - include_tasks: 'tasks/deploy.yml'
  
- hosts: "new_windows"
  gather_facts: true
  tasks:

  #- name: Base | Enable .NET Windows features
  #  win_feature:
  #    name: as-net-framework, web-asp-net45
  #    state: present

  #- name: Base | Install .NET framework
  #  win_package:
  #    path: "https://download.microsoft.com/download/E/4/1/E4173890-A24A-4936-9FC9-AF930FE3FA40/NDP461-KB3102436-x86-x64-AllOS-ENU.exe"
  #    product_id: "{BD6F5371-DAC1-30F0-9DDE-CAC6791E28C3}"
  #    state: present
  #    arguments: /q /norestart


  - name: Running systeminfo (just to test WinRM connection)
    win_command: cmd.exe /c systeminfo
    args:
      chdir: "c:/windows/temp"
    register: systeminfo

  - debug: msg="{{ systeminfo['stdout_lines'] }}"


