---
- hosts: all
  gather_facts: false
  vars_files:
    - vars.yml

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    vcenter_address: '{{ hostvars[inventory_hostname]["inventory_hostname"] }}'
    esxi_login: &esxi_login
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_login }}'
      password: '{{ vcenter_password }}'   
      datacenter: '{{ vcenter_datacenter }}'
      validate_certs: no  

  tasks:
  #- include_tasks: 'tasks/base.yml'
  

  - name: Set password via vmware_vm_shell
    local_action:
      module: vmware_vm_shell
      <<: *esxi_login
      vm_username: 'Administrator'
      vm_password: '{{ default_password }}'
      vm_id: '{{ vm_name }}'
      vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
      vm_shell_args: '-command "(net user Administrator {{ vm_password_new }})"'
      wait_for_process: true
    ignore_errors: yes
