---
- name: Base | Installing custom python pyvmomi
  ansible.builtin.pip:
    executable: pip3
    state: forcereinstall
    name:
      - git+https://github.com/helviojunior/pyvmomi
  delegate_to: localhost