---
- name: Base | Installing custom python pyvmomi
  ansible.builtin.pip:
    state: forcereinstall
    name:
      - git+https://github.com/helviojunior/pyvmomi
  delegate_to: localhost

- name: Base | Force urllib3 version
  ansible.builtin.pip:
    state: forcereinstall
    name:
      - urllib3==1.26.6 
  delegate_to: localhost

- name: Base | Install Python packages
  ansible.builtin.pip:
    state: install
    name:
      - jmespath
      - requests
      - pywinrm
      - netaddr
      - requests-credssp
  delegate_to: localhost
