---
# Create floppy disk
# Source: https://madlabber.wordpress.com/2019/06/19/using-autounattend-xml-to-enable-ansible-support-in-windows/
# 
– name: Get VCenter Token
  uri:
  url: “https://{{ vcenter_hostname }}/rest/com/vmware/cis/session”
  url_username: “{{ vcenter_login }}”
  url_password: “{{ vcenter_password }}”
  method: POST
  status_code: 200
  register: vcenter_session

– name: Attach Floppy to VM
  uri:
  url: “https://{{ vcenter_hostname }}/rest/vcenter/vm/{{ deploy_vm.instance.moid }}/hardware/floppy”
  headers:
  Cookie: “{{ vcenter_session.set_cookie }}”
  return_content: yes
  method: POST
  status_code: 200
  body:
  spec:
  backing:
  image_file: “[datastore1] ISO/WIN2019-FLOPPY-ISC.flp”
  type: “IMAGE_FILE”
  start_connected: true
  body_format: json
  register: vm_vcenter_floppy

