---
# Create floppy disk
# Source: https://madlabber.wordpress.com/2019/06/19/using-autounattend-xml-to-enable-ansible-support-in-windows/
# 
- name: Floppy | Create local directory 'unattend'
  ansible.builtin.file:
    path: unattend
    state: directory
  register: local_dir
  delegate_to: localhost

- name: Floppy | Creating a step1.ps1 file
  copy:
    dest: "unattend/step1.ps1"
    content: |
      $userAccount = Get-LocalUser -Name "Administrator" -ErrorAction Ignore
      $secPassword = ConvertTo-SecureString "@Pass123456" -AsPlainText -Force -ErrorAction Ignore
      $userAccount | Set-LocalUser -Password $secPassword -ErrorAction Ignore
  delegate_to: localhost

- name: Floppy | Creating a step2.ps1 file
  copy:
    dest: "unattend/step2.ps1"
    content: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Invoke-WebRequest -Uri https://packages.vmware.com/tools/esx/7.0u2/windows/x64/VMware-tools-11.2.5-17337674-x86_64.exe -OutFile C:\Windows\temp\VMware-tools.exe
  delegate_to: localhost

- name: Floppy | Creating a step3.ps1 file
  copy:
    dest: "unattend/step3.ps1"
    content: |
      Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False -ErrorAction Ignore
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Invoke-Expression ((New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/helviojunior/ansible-vmware-windows/main/resources/ConfigureRemotingForAnsible.ps1'))
  delegate_to: localhost

- name: Floppy | Creating a script.cmd file
  copy:
    dest: "unattend/script.cmd"
    content: |
      @echo off
      a:
      cd a:\
      powershell -ExecutionPolicy ByPass -File a:\step1.ps1
      powershell -ExecutionPolicy ByPass -File a:\step2.ps1
      powershell -ExecutionPolicy ByPass -File a:\step3.ps1
      C:\Windows\temp\VMware-tools.exe /S /v"/qn REBOOT=R"
  delegate_to: localhost

- name: Floppy | Creating a autounattend.xml file
  copy:
    dest: "unattend/autounattend.xml"
    content: |
      <!--*************************************************
      Windows Server 2016 Answer File Generator
      Created using Windows AFG found at:
      ;http://www.windowsafg.com

      Installation Notes

      Modified to work with the 180day EVAL ISO:
      -Added <InstallFrom>...</InstallFrom> 
      -removed the <productkey> section 

      Modified to enable WinRM for Ansible
      -Added <logoncount>1</logoncount>
      -Added <FirstLogonCommands>...</FirstLogonCommands>

      **************************************************-->

      <?xml version="1.0" encoding="utf-8"?>
      <unattend xmlns="urn:schemas-microsoft-com:unattend">
      <settings pass="windowsPE">
      <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <SetupUILanguage>
      <UILanguage>en-US</UILanguage>
      </SetupUILanguage>
      <InputLocale>0c09:00000409</InputLocale>
      <SystemLocale>en-US</SystemLocale>
      <UILanguage>en-US</UILanguage>
      <UILanguageFallback>en-US</UILanguageFallback>
      <UserLocale>en-US</UserLocale>
      </component>
      <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <ImageInstall>
      <OSImage>
      <InstallTo>
      <DiskID>0</DiskID>
      <PartitionID>2</PartitionID>
      </InstallTo>
          <InstallFrom>
          <MetaData wcm:action="add">
                <Key>/IMAGE/INDEX</Key>
                <Value>2</Value>
            </MetaData>
          </InstallFrom>
      </OSImage>
      </ImageInstall>
      <UserData>
      <AcceptEula>true</AcceptEula>
      <FullName>Administrator</FullName>
      <Organization>Organization</Organization>
      </UserData>
      <EnableFirewall>true</EnableFirewall>
      <DiskConfiguration>
      <Disk wcm:action="add">
      <CreatePartitions>
      <CreatePartition wcm:action="add">
      <Order>1</Order>
      <Size>350</Size>
      <Type>Primary</Type>
      </CreatePartition>
      <CreatePartition wcm:action="add">
      <Extend>true</Extend>
      <Order>2</Order>
      <Type>Primary</Type>
      </CreatePartition>
      </CreatePartitions>
      <ModifyPartitions>
      <ModifyPartition wcm:action="add">
      <Format>NTFS</Format>
      <Label>System</Label>
      <Order>1</Order>
      <PartitionID>1</PartitionID>
      <TypeID>0x27</TypeID>
      </ModifyPartition>
      <ModifyPartition wcm:action="add">
      <Order>2</Order>
      <PartitionID>2</PartitionID>
      <Letter>C</Letter>
      <Label>System</Label>
      <Format>NTFS</Format>
      </ModifyPartition>
      </ModifyPartitions>
      <DiskID>0</DiskID>
      <WillWipeDisk>true</WillWipeDisk>
      </Disk>
      </DiskConfiguration>
      </component>
      </settings>
      <settings pass="offlineServicing">
      <component name="Microsoft-Windows-LUA-Settings" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <EnableLUA>false</EnableLUA>
      </component>
      </settings>
      <settings pass="generalize">
      <component name="Microsoft-Windows-Security-SPP" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <SkipRearm>1</SkipRearm>
      </component>
      </settings>
      <settings pass="specialize">
      <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <InputLocale>0409:00000409</InputLocale>
      <SystemLocale>en-US</SystemLocale>
      <UILanguage>en-US</UILanguage>
      <UILanguageFallback>en-US</UILanguageFallback>
      <UserLocale>en-US</UserLocale>
      </component>
      <component name="Microsoft-Windows-Security-SPP-UX" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <SkipAutoActivation>true</SkipAutoActivation>
      </component>
      <component name="Microsoft-Windows-SQMApi" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <CEIPEnabled>0</CEIPEnabled>
      </component>
      <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <ComputerName></ComputerName>
      </component>
      </settings>
      <settings pass="oobeSystem">
      <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <AutoLogon>
        <Password>
          <Value>{{ default_password }}</Value>
          <PlainText>true</PlainText>
        </Password>
        <Enabled>true</Enabled>
        <Username>Administrator</Username>
          <LogonCount>1</LogonCount>
      </AutoLogon>
      <FirstLogonCommands>
          <SynchronousCommand wcm:action="add">
            <Order>1</Order>
            <CommandLine>a:\script.cmd</CommandLine>
          </SynchronousCommand>
      </FirstLogonCommands>  
      <OOBE>
      <HideEULAPage>true</HideEULAPage>
      <HideLocalAccountScreen>true</HideLocalAccountScreen>
      <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
      <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
      <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
      <NetworkLocation>Work</NetworkLocation>
      <ProtectYourPC>3</ProtectYourPC>
      <SkipMachineOOBE>true</SkipMachineOOBE>
      <SkipUserOOBE>true</SkipUserOOBE>
      </OOBE>
      <UserAccounts>
      <AdministratorPassword>
      <Value>{{ default_password }}</Value>
      <PlainText>true</PlainText>
      </AdministratorPassword>
      <LocalAccounts>
      <LocalAccount wcm:action="add">
      <Description>Administrator</Description>
      <DisplayName>Administrator</DisplayName>
      <Group>Administrators</Group>
      <Name>Administrator</Name>
      </LocalAccount>
      </LocalAccounts>
      </UserAccounts>
      <RegisteredOrganization>Organization</RegisteredOrganization>
      <RegisteredOwner>Administrator</RegisteredOwner>
      <DisableAutoDaylightTimeSet>false</DisableAutoDaylightTimeSet>
      <TimeZone>Pacific Standard Time</TimeZone>
      </component>
      </settings>
      </unattend>
  delegate_to: localhost

- name: Floppy | Removing old release
  shell: |
    rm -rf floppy.dmg
  delegate_to: localhost
  ignore_errors: yes

- name: Floppy | Generating floppy image
  shell: |
    hdiutil create -size 1440k -fs "MS-DOS FAT12" -layout NONE -srcfolder unattend -format UDRW -ov floppy.dmg
  delegate_to: localhost
  retries: 10
  delay: 10
  until: "new_image is not failed"
  ignore_errors: yes
  register: new_image

- name: Floppy | Copy to floppy.flp
  copy:
    src: floppy.dmg
    dest: server2016eval.flp
  delegate_to: localhost
  when: new_image.rc == 0

- name: Floppy | Copy standard image to floppy.flp
  copy:
    src: resources/server2016eval.flp
    dest: server2016eval.flp
  delegate_to: localhost
  when: new_image.rc != 0

- name: Floppy | Delete local directory 'unattend'
  file:
    state: absent
    path: unattend
  delegate_to: localhost

- name: Floppy | Delete floppy.dmg
  file:
    state: absent
    path: floppy.dmg
  delegate_to: localhost
  when: new_image.rc == 0

